### ISSUE TITLE
Une erreur survient quand plus de 2 requêtes sont reçues et traitées en même temps

### ISSUE THREAD

**Issue by GODOmegaPi** [Note-thing/backend#62]
Faire deux POST successif (rapides) sur l'endpoint `tags` lève une erreur:
```
app_1  | F, [2022-01-08T15:13:39.085462 #1] FATAL -- :
app_1  | F, [2022-01-08T15:13:39.086584 #1] FATAL -- : ArgumentError (A copy of Api::V1 has been removed from the module tree but is still active!):
app_1  | F, [2022-01-08T15:13:39.086732 #1] FATAL -- :
app_1  | F, [2022-01-08T15:13:39.086831 #1] FATAL -- : activesupport (5.2.6) lib/active_support/dependencies.rb:495:in `load_missing_constant'
app_1  | activesupport (5.2.6) lib/active_support/dependencies.rb:195:in `const_missing'
app_1  | activesupport (5.2.6) lib/active_support/inflector/methods.rb:285:in `const_get'
app_1  | activesupport (5.2.6) lib/active_support/inflector/methods.rb:285:in `block in constantize'
app_1  | activesupport (5.2.6) lib/active_support/inflector/methods.rb:281:in `each'
app_1  | activesupport (5.2.6) lib/active_support/inflector/methods.rb:281:in `inject'
app_1  | activesupport (5.2.6) lib/active_support/inflector/methods.rb:281:in `constantize'
app_1  | activesupport (5.2.6) lib/active_support/dependencies.rb:582:in `get'
app_1  | activesupport (5.2.6) lib/active_support/dependencies.rb:613:in `constantize'
app_1  | actionpack (5.2.6) lib/action_dispatch/http/request.rb:88:in `controller_class_for'
app_1  | actionpack (5.2.6) lib/action_dispatch/http/parameters.rb:101:in `binary_params_for?'
app_1  | actionpack (5.2.6) lib/action_dispatch/http/parameters.rb:92:in `set_binary_encoding'
app_1  | actionpack (5.2.6) lib/action_dispatch/http/parameters.rb:69:in `path_parameters='
app_1  | actionpack (5.2.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
app_1  | actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
app_1  | actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
app_1  | actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
app_1  | rack (2.2.3) lib/rack/etag.rb:27:in `call'
app_1  | rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
app_1  | rack (2.2.3) lib/rack/head.rb:12:in `call'
app_1  | activerecord (5.2.6) lib/active_record/migration.rb:559:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
app_1  | activesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
app_1  | web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
app_1  | web-console (3.7.0) lib/web_console/middleware.rb:22:in `block in call'
app_1  | web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
app_1  | web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
app_1  | railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'
app_1  | railties (5.2.6) lib/rails/rack/logger.rb:28:in `call'
app_1  | sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
app_1  | rack (2.2.3) lib/rack/runtime.rb:22:in `call'
app_1  | activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1  | actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
app_1  | rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
app_1  | rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
app_1  | railties (5.2.6) lib/rails/engine.rb:524:in `call'
app_1  | puma (3.12.6) lib/puma/configuration.rb:227:in `call'
app_1  | puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
app_1  | puma (3.12.6) lib/puma/server.rb:476:in `process_client'
app_1  | puma (3.12.6) lib/puma/server.rb:334:in `block in run'
app_1  | puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by Double-i** [comment]
C'est la même erreur que j'ai rencontré mais sur d'autres endpoints  et avec GET
![image](https://user-images.githubusercontent.com/19327496/148663895-badedb9c-e100-4f59-b7db-b4b368b69e5e.png)

**Comment by EricB2A** [comment]
Yo, 
cette erreur provient du hot-reload, qui n'est que présent en mode de développement. 
Le fix est rapide, je vous le met sur la branche `main`, vous pouvez pull. 

Si vous souhaitez garder le hot-reload (car vous travaillez sur le backend), dé-commentez les lignes (cf. ce [commit](https://github.com/Note-thing/backend/commit/e82cfa33f26a0e01b802fc569c6d31d1da244c7d)).

Faites-moi signe si cette erreur réapparait.
